# Generated by Django 3.1.7 on 2021-03-26 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjCordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.IntegerField(default=0)),
                ('obj_name', models.CharField(max_length=50)),
                ('x_min', models.IntegerField(default=0)),
                ('y_min', models.IntegerField(default=0)),
                ('x_max', models.IntegerField(default=0)),
                ('y_max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='images')),
                ('xmlfile', models.FileField(upload_to='xmlfiles')),
                ('objs_found', models.ImageField(blank=True, upload_to='obj_found_imgs')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
